# Generated by Django 3.0.8 on 2023-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
