# Generated by Django 3.0.8 on 2023-07-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_birth_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term',
            new_name='title',
        ),
    ]
